### ISSUE TITLE
Available on Swiggy/Zomato clickable button on Home Page

### ISSUE THREAD

**Issue by birajpoddar** [birajpoddar/masala-nama#15]

**Comment by balvinderSingh1987** [comment]
Zomato - https://www.zomato.com/ajmer/masala-nama-ana-sagar-lake
Swiggy - https://www.swiggy.com/restaurants/masala-nama-sagar-link-road-north-ajmer-ajmer-659627

**Comment by birajpoddar** [comment]
Compled as per last tagged commit
